name: Environment-Specific Workflow
on:
  push:
    branches:
      - test_deploy_prod
      - test_deploy_dev
      - test_deploy_stage

env:
  DEPLOY_ENV: ${{ 
    github.ref == 'refs/heads/test_deploy_prod' && 'prod' || 
    github.ref == 'refs/heads/test_deploy_stage' && 'stage' || 
    github.ref == 'refs/heads/test_deploy_dev' && 'dev' 
    }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ env.DEPLOY_ENV }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Debug Info
        run: |
          echo "Branch name: ${{ github.ref }}"
          echo "Current environment: ${{ github.event.deployment_status.environment }}"
          echo "TEST_1 env var: ${{ vars.TEST_1 }}"

  another-job:
    runs-on: ubuntu-latest
    environment: ${{ env.DEPLOY_ENV }}
    steps:
      - name: Some other task
        run: |
          echo "Branch name: ${{ github.ref }}"
          echo "Current environment: ${{ github.event.deployment_status.environment }}"
          echo "TEST_1 env var: ${{ vars.TEST_1 }}"
