name: Environment-Specific Workflow
on:
  push:
    branches:
      - test_deploy_prod
      - test_deploy_dev
      - test_deploy_stage

jobs:
  determine-env:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ 
        github.ref == 'refs/heads/test_deploy_prod' && 'prod' || 
        github.ref == 'refs/heads/test_deploy_stage' && 'stage' || 
        github.ref == 'refs/heads/test_deploy_dev' && 'dev' 
        }}
    steps:
      - run: echo "Determined environment"

  deploy:
    needs: determine-env
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-env.outputs.env_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Debug Info
        run: |
          echo "Branch name: ${{ github.ref }}"
          echo "Current environment: ${{ github.event.deployment_status.environment }}"
          echo "TEST_1 env var: ${{ vars.TEST_1 }}"

  another-job:
    needs: determine-env
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-env.outputs.env_name }}
    steps:
      - name: Some other task
        env:
          SQS_CHANNELS_JSON: ${{ vars.SQS_CHANNELS_JSON }}
        run: |
          echo "SQS Channels = ${SQS_CHANNELS_JSON:-'[]'}"
          echo "TEST_1 env var: ${{ vars.TEST_1 }}"
