name: Environment-Specific Workflow

on:
  push:
    branches:
      - test_deploy_prod
      - test_deploy_dev
      - test_deploy_stage

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/test_deploy_prod' ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == 'refs/heads/test_deploy_stage' ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == 'refs/heads/test_deploy_dev' ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: set-environment
    runs-on: ubuntu-latest
    environment: ${{ needs.set-environment.outputs.env_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # Your deployment steps

  another-job:
    needs: set-environment
    runs-on: ubuntu-latest
    environment: ${{ needs.set-environment.outputs.env_name }}
    steps:
      - name: Some other steps
        run: echo "Using same environment"
